apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brent-verlinden-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iDqrks/milestone2-kubernetes.git
    targetRevision: main
    path: kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: brent-verlinden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
