apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bv-tls
  namespace: brent-verlinden
spec:
  secretName: bv-tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  commonName: brent-verlinden.local
  dnsNames:
  - brent-verlinden.local
