apiVersion: v1
kind: Secret
metadata:
  name: bv-secrets
  namespace: brent-verlinden
type: Opaque
data:
  DB_PASSWORD: "YnJlbnRfcGFzc3dvcmQ="  # brent_password in base64
  MYSQL_ROOT_PASSWORD: "cm9vdF9wYXNzd29yZA=="  # root_password in base64
