apiVersion: v1
kind: Service
metadata:
  name: bv-mariadb
  namespace: brent-verlinden
spec:
  selector:
    app: bv-mariadb
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None  # Headless service voor stateful sets
